pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Clone the repository
                git branch: 'main', url: 'https://github.com/rohankaranje/intern-ass-2.git'
            }
        }

        stage('Build') {
            steps {
                // Compile the Maven project
                bat 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                // Run unit tests
                bat 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                // Example deploy step (you can modify this to fit your deployment needs)
                echo 'Deploying the application...'
            }
        }
    }

    post {
        success {
            echo 'Build and deployment successful.'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
